### ISSUE TITLE
winq_node needs restart

### ISSUE THREAD

**Issue by jelle-e** [qlcchain/WinQ-Server#3]
Description of bug:

Steps to reproduce the issue:
keep winq_node running for about two weeks on Debian 9.5...

Describe the results you received:
suddenly the asset isn't reachable anymore. Asset shows green in WinQ, but no connection is made.

Describe the results you expected:
expected connection

Environment:
Server: Debian 9.5 with only winq_node docker running (vpn turned off)

logs:
where to find the logs?

**Comment by pwc5232759** [comment]
Ok, thank you very much for your feedback. I guess the reason is related to the interface of the transfer configuration file. I will solve it as soon as possible. After the solution, I will re-upload the docker image. You will need to re-run start.sh

**Comment by pwc5232759** [comment]
Hi，jelle，I think this bug has been solved，I already update docker image on the dockerhub and you just have to run start.sh
